[package]
name = "specter_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "specter_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.23.0"
uuid = "0.8"
webrtc = "0.4.0"
